---
dependencies:
  - role: pacman
    when: ansible_facts['distribution'] == "Archlinux"
  - role: systemd-resolved
  - role: ufw
  - role: ssh
    vars:
      enable_agent: "{{ ssh_enable_agent }}"
      cert_renewal_mode: "{{ ssh_cert_renewal_mode }}"
  - role: tailscale
  - role: ansible
  - role: terminal
    when: ansible_facts['distribution'] == "Archlinux"
  - role: tls
