---
- name: Update CA certificates (Arch Linux)
  ansible.builtin.command: /usr/bin/update-ca-trust
  become: true
  listen: "Update CA certificates"
  when: ansible_facts['distribution'] == "Archlinux"
  changed_when: true

- name: Update CA certificates (Ubuntu)
  ansible.builtin.command: /usr/sbin/update-ca-certificates
  become: true
  listen: "Update CA certificates"
  when: ansible_facts['distribution'] == "Ubuntu"
  changed_when: true
