---
dependencies:
  - role: common
    vars:
      ssh_enable_agent: true
  - role: physical
  - role: plasma
  - role: flatpak
  - role: docker
  - role: incus
  - role: plymouth
  - role: yubikey
  - role: syncthing
  - role: apparmor
  - role: lockdown
