---
dependencies:
  - role: systemd-resolved
  - role: systemd-networkd
    vars:
      profile: "simple"
  - role: ufw
  - role: ssh
  - role: tailscale
  - role: ansible
  - role: tls
  # need to setup repo and packages
  # - role: docker
