---
dependencies:
  - role: systemd-resolved
  - role: systemd-networkd
    vars:
      profile: "simple"
  - role: ufw
  # check over everything
  # - role: ssh
  # need to setup repo and packages
  # - role: tailscale
  # needs to modify packages array
  # - role: ansible
  # basically needs everything rewritten
  # - role: tls
  # need to setup repo and packages
  # - role: docker
