---
dependencies:
  - role: common
    vars:
      ssh_cert_renewal_mode: "step"
  - role: apparmor
  - role: lockdown
  - role: physical
    vars:
      uki_root_disk_mode: "raid1"
  - role: incus
    vars:
      startup_mode: "on-boot"
