---
- name: Install tailscale packages
  community.general.pacman:
    name:
      - tailscale
    state: present
  become: true
  when: ansible_facts['distribution'] == "Archlinux"

- name: Set up tailscale apt key
  ansible.builtin.get_url:
    url: https://pkgs.tailscale.com/stable/ubuntu/{{ ansible_distribution_release }}.noarmor.gpg
    dest: /usr/share/keyrings/tailscale-archive-keyring.gpg
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: true
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Set up tailscale apt repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/tailscale-archive-keyring.gpg] https://pkgs.tailscale.com/stable/ubuntu {{ ansible_distribution_release }} main"
    filename: tailscale
    state: present
  become: true
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Enable tailscaled
  ansible.builtin.systemd_service:
    name: tailscaled
    enabled: true
    state: started
  become: true
